interface ITBase<T> {
    [key: string]: T;
}
interface IT_TableMap {
    readonly AidHeroSetting?: ITBase<IT_AidHeroSetting>;
    readonly AidTypeSetting?: ITBase<IT_AidTypeSetting>;
    readonly ArenaRobotSetting?: ITBase<IT_ArenaRobotSetting>;
    readonly ChallengeRewardSetting?: ITBase<IT_ChallengeRewardSetting>;
    readonly ConfigValue?: ITBase<IT_ConfigValue>;
    readonly RankRewardSetting?: ITBase<IT_RankRewardSetting>;
    readonly D3SceneSetting?: ITBase<IT_D3SceneSetting>;
    readonly ObjTypeD3SceneSetting?: IT_ObjTypeD3SceneSetting;
}
interface IT_AidHeroSetting {
    /** 主键 */
    readonly id?: number;
    /** 普攻技能配置标识 */
    readonly commonId?: number;
    /** 大招技能配置标识 */
    readonly ultimateId?: number;
    /** 死亡技能配置标识 */
    readonly deadId?: number;
    /** 进场技能配置标识 */
    readonly startId?: number;
    /** 英雄base标识 */
    readonly base?: number;
    /** 稀有度 */
    readonly rarity?: number;
    /** 模型 */
    readonly model?: number;
    /** 羁绊配置标识 */
    readonly bondageId?: number;
    /** 等级 */
    readonly level?: number;
    /** 战斗力 */
    readonly fightPower?: number;
    /** 星级 */
    readonly star?: number;
    /** 名称 */
    readonly name?: string;
    /** 元素 */
    readonly element?: string;
    /** 职业 */
    readonly profession?: string;
    /** 模拟战斗行为控制id(关联SimulatedActSetting) */
    readonly simulate_act?: number;
    readonly attributes?: {
        /** 物理攻击 */
        readonly STR?: undefined;
        /** 生命值 */
        readonly HP?: undefined;
        /** 护甲 */
        readonly ARMOR?: undefined;
        /** 法防（千倍） */
        readonly REST?: undefined;
        /** 命中率（千倍） */
        readonly HIT?: undefined;
        /** 闪避率（千倍） */
        readonly DODGE?: undefined;
        /** 暴击率（千倍） */
        readonly CRIT?: undefined;
        /** 暴击伤害加深（千倍） */
        readonly DEEPEN?: undefined;
        /** 格挡率（千倍） */
        readonly BLOCK?: undefined;
        /** 格挡减伤（千倍） */
        readonly REDUCE?: undefined;
        /** 真实伤害（千倍） */
        readonly REAL?: undefined;
        /** 生命值上限 */
        readonly HP_MAX?: undefined;
        /** 能量值 */
        readonly MP?: undefined;
        /** 能量值上限 */
        readonly MP_MAX?: undefined;
        /** 自动回能值 */
        readonly MP_INCR?: undefined;
        /** 大招能量 */
        readonly ULTIMATE_MP?: undefined;
        /** 待机间隔 */
        readonly IDLE_INTERVAL?: undefined;
        /** 横向移动间隔 */
        readonly MOVE_INTERVAL?: undefined;
        /** 斜向移动间隔 */
        readonly MOVE_DIAG_INTERVAL?: undefined;
        /** 跳跃间隔时间 */
        readonly JUMP_INTERVAL?: undefined;
        /** 最大移动距离 */
        readonly MOVE_LIMITED?: undefined;
    };
}
interface IT_AidTypeSetting {
    /** 援军类型 */
    readonly aidType?: string;
    /** 可使用次数(不存在为无限次使用) */
    readonly counts?: { [key: string]: number };
    /** 重置时间(不填为不可重置) */
    readonly timingKey?: string;
    /** 单次可上阵数量限制(-1为不限制) */
    readonly onceCount?: number;
    /** 是否临时获得 */
    readonly isTempGet?: boolean;
    /** 是否配置提供 */
    readonly isAidSetting?: boolean;
}
interface IT_ArenaRobotSetting {
    /** 机器人ID */
    readonly id?: number;
    /** 玩家名 */
    readonly name?: string;
    /** 战斗力 */
    readonly power?: number;
    /** 模型ID */
    readonly model?: number;
    /** 头像框ID */
    readonly frame?: number;
    /** 怪物配置{@link NpcSetting#getId()} */
    readonly npcId?: number;
}
interface IT_ChallengeRewardSetting {}
interface IT_ConfigValue {
    /** 主键 */
    readonly id?: string;
    /** 客户端配置 */
    readonly value?: any;
}
interface IT_RankRewardSetting {
    /** 阶段 */
    readonly step?: number;
    /** 排行奖励 */
    readonly rewards?: any;
}
interface IT_D3SceneSetting {
    /** 主键 */
    readonly key?: string;
    /** 场景 */
    readonly scene?: string;
}
interface IT_ObjTypeD3SceneSetting {
    /** 挂机默认场景 */
    readonly Simulated?: string;
    /** 推图默认场景 */
    readonly Dungeon?: string;
    /** xxx默认 */
    readonly Avalon?: string;
    /** 竞技场 */
    readonly Area?: string;
    /** 哈哈默认 */
    readonly Mystery?: string;
    readonly MyObject?: {
        /** 对象测试:主键id */
        readonly id?: undefined;
        /** 名字 */
        readonly name?: undefined;
    };
}
